In [1]:
import duckdb

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [23]:
df = con.execute("""
                 select *
                 from (
                 select *, row_number() over (partition by natbr order by data_ingestao desc) as row 
                 from bronze_produtos
                 where data_ingestao >= '2025-10-29'
                 ) where row = 1
                 """).fetchdf()
df.head()

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_arquivo,data_ingestao,row
0,10003,PREGO,BT10,100,60S,z0019_2.csv,2025-10-29 13:47:39.477179,1
1,10004,SERRA,BT50,100,200,z0019_2.csv,2025-10-29 13:47:39.477179,1
2,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2025-10-29 13:34:41.848108,1
3,10002,MARTELO,BT50,100,1500,z0019_1.csv,2025-10-29 13:34:41.848108,1
4,10005,MACHADO,BT50,100,100,z0019_2.csv,2025-10-29 13:47:39.477179,1

In [4]:
df_final = df.drop(columns=['nome_arquivo', 'data_ingestao', 'row'])
df_final = df_final.rename(columns={"NATBR": "id"})
df_final = df_final.rename(columns={"MAKTX": "nm_produto"})
df_final = df_final.rename(columns={"WERKS": "id_categoria"})
df_final = df_final.rename(columns={"MAINS": "id_fornecedor"})
df_final = df_final.rename(columns={"LABST": "vl_preco"})
df_final.head()

      id nm_produto id_categoria id_fornecedor vl_preco
0  10002    MARTELO         BT50           100     1500
1  10001   PARAFUSO         BT10           100      100
2  10005    MACHADO         BT50           100      100
3  10004      SERRA         BT50           100      200
4  10003      PREGO         BT10           100      60S

In [18]:
df2 = df_final

df2.dtypes

id               object
nm_produto       object
id_categoria     object
id_fornecedor    object
vl_preco         object
dtype: object

In [6]:
df_final.dtypes

id               object
nm_produto       object
id_categoria     object
id_fornecedor    object
vl_preco         object
dtype: object

In [ ]:
df2 = df_final
df2 = df2.astype(
    {
    "id": int,
    "nm_produto": str,
    "id_categoria": str,
    "id_fornecedor": int,
    "vl_preco": int
    }
)
df2.head(10)

In [22]:
df2 = df_final
df2 = df2.astype(
    {
        'id': int,
        'nm_produto': str,
        'id_categoria': str,
        'id_fornecedor': str,
        'vl_preco': str
    }
)

df2.dtypes

id                int64
nm_produto       object
id_categoria     object
id_fornecedor    object
vl_preco         object
dtype: object